type TCountry = {
	name: string;
	flag: string;
};

export const countries: TCountry[] = [
	{ name: "Kingdom of Saudi Arabia", flag: "https://flagcdn.com/sa.svg" },
	{ name: "Republic of Cameroon", flag: "https://flagcdn.com/cm.svg" },
	{ name: "Islamic Republic of Iran", flag: "https://flagcdn.com/ir.svg" },
	{ name: "United Arab Emirates", flag: "https://flagcdn.com/ae.svg" },
	{ name: "Ukraine", flag: "https://flagcdn.com/ua.svg" },
	{ name: "Republic of Benin", flag: "https://flagcdn.com/bj.svg" },
	{ name: "Federation of Saint Christopher and Nevis", flag: "https://flagcdn.com/kn.svg" },
	{ name: "British Indian Ocean Territory", flag: "https://flagcdn.com/io.svg" },
	{ name: "Republic of Indonesia", flag: "https://flagcdn.com/id.svg" },
	{ name: "Togolese Republic", flag: "https://flagcdn.com/tg.svg" },
	{ name: "Nation of Brunei, Abode of Peace", flag: "https://flagcdn.com/bn.svg" },
	{ name: "Czech Republic", flag: "https://flagcdn.com/cz.svg" },
	{ name: "Republic of Serbia", flag: "https://flagcdn.com/rs.svg" },
	{ name: "Independent State of Papua New Guinea", flag: "https://flagcdn.com/pg.svg" },
	{ name: "Republic of Nauru", flag: "https://flagcdn.com/nr.svg" },
	{ name: "Bermuda", flag: "https://flagcdn.com/bm.svg" },
	{ name: "Bolivarian Republic of Venezuela", flag: "https://flagcdn.com/ve.svg" },
	{ name: "Department of Mayotte", flag: "https://flagcdn.com/yt.svg" },
	{ name: "Romania", flag: "https://flagcdn.com/ro.svg" },
	{ name: "Tuvalu", flag: "https://flagcdn.com/tv.svg" },
	{ name: "State of Palestine", flag: "https://flagcdn.com/ps.svg" },
	{ name: "People's Republic of China", flag: "https://flagcdn.com/cn.svg" },
	{ name: "Democratic Socialist Republic of Sri Lanka", flag: "https://flagcdn.com/lk.svg" },
	{ name: "Republic of South Africa", flag: "https://flagcdn.com/za.svg" },
	{ name: "Bailiwick of Guernsey", flag: "https://flagcdn.com/gg.svg" },
	{ name: "United Republic of Tanzania", flag: "https://flagcdn.com/tz.svg" },
	{ name: "Guadeloupe", flag: "https://flagcdn.com/gp.svg" },
	{ name: "Faroe Islands", flag: "https://flagcdn.com/fo.svg" },
	{ name: "Tokelau", flag: "https://flagcdn.com/tk.svg" },
	{ name: "Malaysia", flag: "https://flagcdn.com/my.svg" },
	{ name: "Republic of India", flag: "https://flagcdn.com/in.svg" },
	{ name: "Territory of the French Southern and Antarctic Lands", flag: "https://flagcdn.com/tf.svg" },
	{ name: "Gibraltar", flag: "https://flagcdn.com/gi.svg" },
	{ name: "Territory of Norfolk Island", flag: "https://flagcdn.com/nf.svg" },
	{ name: "Republic of the Sudan", flag: "https://flagcdn.com/sd.svg" },
	{ name: "Saint Vincent and the Grenadines", flag: "https://flagcdn.com/vc.svg" },
	{ name: "Virgin Islands", flag: "https://flagcdn.com/vg.svg" },
	{ name: "French Polynesia", flag: "https://flagcdn.com/pf.svg" },
	{ name: "Principality of Monaco", flag: "https://flagcdn.com/mc.svg" },
	{ name: "Federal Democratic Republic of Nepal", flag: "https://flagcdn.com/np.svg" },
	{ name: "Republic of Uzbekistan", flag: "https://flagcdn.com/uz.svg" },
	{ name: "Republic of Fiji", flag: "https://flagcdn.com/fj.svg" },
	{ name: "Republic of Mauritius", flag: "https://flagcdn.com/mu.svg" },
	{ name: "Montenegro", flag: "https://flagcdn.com/me.svg" },
	{ name: "Independent and Sovereign Republic of Kiribati", flag: "https://flagcdn.com/ki.svg" },
	{ name: "Republic of Equatorial Guinea", flag: "https://flagcdn.com/gq.svg" },
	{ name: "Heard Island and McDonald Islands", flag: "https://flagcdn.com/hm.svg" },
	{ name: "Republic of the Philippines", flag: "https://flagcdn.com/ph.svg" },
	{ name: "Svalbard og Jan Mayen", flag: "https://flagcdn.com/sj.svg" },
	{ name: "Territory of the Cocos (Keeling) Islands", flag: "https://flagcdn.com/cc.svg" },
	{ name: "Republic of Mozambique", flag: "https://flagcdn.com/mz.svg" },
	{ name: "Republic of Suriname", flag: "https://flagcdn.com/sr.svg" },
	{ name: "Republic of Senegal", flag: "https://flagcdn.com/sn.svg" },
	{ name: "Syrian Arab Republic", flag: "https://flagcdn.com/sy.svg" },
	{ name: "Kingdom of Lesotho", flag: "https://flagcdn.com/ls.svg" },
	{ name: "Virgin Islands of the United States", flag: "https://flagcdn.com/vi.svg" },
	{ name: "Republic of Cabo Verde", flag: "https://flagcdn.com/cv.svg" },
	{ name: "New Zealand", flag: "https://flagcdn.com/nz.svg" },
	{ name: "Republic of Latvia", flag: "https://flagcdn.com/lv.svg" },
	{ name: "Islamic Republic of Mauritania", flag: "https://flagcdn.com/mr.svg" },
	{ name: "Republic of Sierra Leone", flag: "https://flagcdn.com/sl.svg" },
	{ name: "Kingdom of Thailand", flag: "https://flagcdn.com/th.svg" },
	{ name: "United Kingdom of Great Britain and Northern Ireland", flag: "https://flagcdn.com/gb.svg" },
	{ name: "Republic of Iraq", flag: "https://flagcdn.com/iq.svg" },
	{ name: "Federal Republic of Nigeria", flag: "https://flagcdn.com/ng.svg" },
	{ name: "Republic of Rwanda", flag: "https://flagcdn.com/rw.svg" },
	{ name: "State of Libya", flag: "https://flagcdn.com/ly.svg" },
	{ name: "Commonwealth of Australia", flag: "https://flagcdn.com/au.svg" },
	{ name: "Republic of Paraguay", flag: "https://flagcdn.com/py.svg" },
	{ name: "Republic of Finland", flag: "https://flagcdn.com/fi.svg" },
	{ name: "Republic of San Marino", flag: "https://flagcdn.com/sm.svg" },
	{ name: "Commonwealth of the Bahamas", flag: "https://flagcdn.com/bs.svg" },
	{ name: "Commonwealth of Dominica", flag: "https://flagcdn.com/dm.svg" },
	{ name: "Republic of Niger", flag: "https://flagcdn.com/ne.svg" },
	{ name: "Saint Helena, Ascension and Tristan da Cunha", flag: "https://flagcdn.com/sh.svg" },
	{ name: "Solomon Islands", flag: "https://flagcdn.com/sb.svg" },
	{ name: "Union of the Comoros", flag: "https://flagcdn.com/km.svg" },
	{ name: "Republic of Ghana", flag: "https://flagcdn.com/gh.svg" },
	{ name: "United States of America", flag: "https://flagcdn.com/us.svg" },
	{ name: "Republic of Malta", flag: "https://flagcdn.com/mt.svg" },
	{ name: "Kingdom of Sweden", flag: "https://flagcdn.com/se.svg" },
	{ name: "Federative Republic of Brazil", flag: "https://flagcdn.com/br.svg" },
	{ name: "Hellenic Republic", flag: "https://flagcdn.com/gr.svg" },
	{ name: "Republic of Namibia", flag: "https://flagcdn.com/na.svg" },
	{ name: "Republic of Estonia", flag: "https://flagcdn.com/ee.svg" },
	{ name: "Kingdom of Tonga", flag: "https://flagcdn.com/to.svg" },
	{ name: "Islamic Republic of Pakistan", flag: "https://flagcdn.com/pk.svg" },
	{ name: "Isle of Man", flag: "https://flagcdn.com/im.svg" },
	{ name: "Plurinational State of Bolivia", flag: "https://flagcdn.com/bo.svg" },
	{ name: "Republic of Cyprus", flag: "https://flagcdn.com/cy.svg" },
	{ name: "South Georgia and the South Sandwich Islands", flag: "https://flagcdn.com/gs.svg" },
	{ name: "Kyrgyz Republic", flag: "https://flagcdn.com/kg.svg" },
	{ name: "Republic of Honduras", flag: "https://flagcdn.com/hn.svg" },
	{ name: "Antigua and Barbuda", flag: "https://flagcdn.com/ag.svg" },
	{ name: "Republic of the Congo", flag: "https://flagcdn.com/cg.svg" },
	{
		name: "Hong Kong Special Administrative Region of the People's Republic of China",
		flag: "https://flagcdn.com/hk.svg",
	},
	{ name: "Italian Republic", flag: "https://flagcdn.com/it.svg" },
	{ name: "Republic of Cuba", flag: "https://flagcdn.com/cu.svg" },
	{ name: "Antarctica", flag: "https://flagcdn.com/aq.svg" },
	{ name: "Sultanate of Oman", flag: "https://flagcdn.com/om.svg" },
	{ name: "Vatican City State", flag: "https://flagcdn.com/va.svg" },
	{ name: "Kingdom of Bahrain", flag: "https://flagcdn.com/bh.svg" },
	{ name: "Oriental Republic of Uruguay", flag: "https://flagcdn.com/uy.svg" },
	{ name: "Republic of Yemen", flag: "https://flagcdn.com/ye.svg" },
	{ name: "Kingdom of Cambodia", flag: "https://flagcdn.com/kh.svg" },
	{ name: "Kingdom of Morocco", flag: "https://flagcdn.com/ma.svg" },
	{ name: "Collectivity of Saint Barth\u00e9lemy", flag: "https://flagcdn.com/bl.svg" },
	{ name: "Republic of Kosovo", flag: "https://flagcdn.com/xk.svg" },
	{ name: "Slovak Republic", flag: "https://flagcdn.com/sk.svg" },
	{ name: "Saint Martin", flag: "https://flagcdn.com/mf.svg" },
	{ name: "Territory of the Wallis and Futuna Islands", flag: "https://flagcdn.com/wf.svg" },
	{ name: "Republic of Botswana", flag: "https://flagcdn.com/bw.svg" },
	{ name: "French Republic", flag: "https://flagcdn.com/fr.svg" },
	{ name: "Kingdom of Spain", flag: "https://flagcdn.com/es.svg" },
	{ name: "Territory of Christmas Island", flag: "https://flagcdn.com/cx.svg" },
	{ name: "Republic of Zambia", flag: "https://flagcdn.com/zm.svg" },
	{ name: "Republic of Croatia", flag: "https://flagcdn.com/hr.svg" },
	{ name: "Republic of Armenia", flag: "https://flagcdn.com/am.svg" },
	{ name: "Republic of Palau", flag: "https://flagcdn.com/pw.svg" },
	{ name: "Republic of Trinidad and Tobago", flag: "https://flagcdn.com/tt.svg" },
	{ name: "Principality of Andorra", flag: "https://flagcdn.com/ad.svg" },
	{ name: "People's Democratic Republic of Algeria", flag: "https://flagcdn.com/dz.svg" },
	{ name: "Federated States of Micronesia", flag: "https://flagcdn.com/fm.svg" },
	{ name: "Belize", flag: "https://flagcdn.com/bz.svg" },
	{ name: "Republic of China (Taiwan)", flag: "https://flagcdn.com/tw.svg" },
	{ name: "Tunisian Republic", flag: "https://flagcdn.com/tn.svg" },
	{ name: "\u00c5land Islands", flag: "https://flagcdn.com/ax.svg" },
	{ name: "Republic of Haiti", flag: "https://flagcdn.com/ht.svg" },
	{ name: "Sint Maarten", flag: "https://flagcdn.com/sx.svg" },
	{ name: "Republic of Chad", flag: "https://flagcdn.com/td.svg" },
	{ name: "Principality of Liechtenstein", flag: "https://flagcdn.com/li.svg" },
	{ name: "Dominican Republic", flag: "https://flagcdn.com/do.svg" },
	{ name: "Bouvet Island", flag: "https://flagcdn.com/bv.svg" },
	{ name: "Central African Republic", flag: "https://flagcdn.com/cf.svg" },
	{ name: "Republic of Austria", flag: "https://flagcdn.com/at.svg" },
	{ name: "Republic of Singapore", flag: "https://flagcdn.com/sg.svg" },
	{ name: "Canada", flag: "https://flagcdn.com/ca.svg" },
	{ name: "Greenland", flag: "https://flagcdn.com/gl.svg" },
	{ name: "Republic of Angola", flag: "https://flagcdn.com/ao.svg" },
	{ name: "Republic of Tajikistan", flag: "https://flagcdn.com/tj.svg" },
	{ name: "Portuguese Republic", flag: "https://flagcdn.com/pt.svg" },
	{ name: "Kingdom of Eswatini", flag: "https://flagcdn.com/sz.svg" },
	{ name: "Federal Republic of Somalia", flag: "https://flagcdn.com/so.svg" },
	{ name: "Co-operative Republic of Guyana", flag: "https://flagcdn.com/gy.svg" },
	{ name: "Republic of C\u00f4te d'Ivoire", flag: "https://flagcdn.com/ci.svg" },
	{ name: "Republic of the Maldives", flag: "https://flagcdn.com/mv.svg" },
	{ name: "Republic of Seychelles", flag: "https://flagcdn.com/sc.svg" },
	{ name: "Aruba", flag: "https://flagcdn.com/aw.svg" },
	{ name: "Arab Republic of Egypt", flag: "https://flagcdn.com/eg.svg" },
	{ name: "Republic of Madagascar", flag: "https://flagcdn.com/mg.svg" },
	{ name: "Republic of Zimbabwe", flag: "https://flagcdn.com/zw.svg" },
	{ name: "Republic of Korea", flag: "https://flagcdn.com/kr.svg" },
	{ name: "State of Eritrea", flag: "https://flagcdn.com/er.svg" },
	{ name: "Jamaica", flag: "https://flagcdn.com/jm.svg" },
	{ name: "Republic of Uganda", flag: "https://flagcdn.com/ug.svg" },
	{ name: "Cayman Islands", flag: "https://flagcdn.com/ky.svg" },
	{ name: "American Samoa", flag: "https://flagcdn.com/as.svg" },
	{ name: "Mongolia", flag: "https://flagcdn.com/mn.svg" },
	{ name: "Grand Duchy of Luxembourg", flag: "https://flagcdn.com/lu.svg" },
	{ name: "Republic of Guinea", flag: "https://flagcdn.com/gn.svg" },
	{ name: "Republic of North Macedonia", flag: "https://flagcdn.com/mk.svg" },
	{ name: "Kingdom of Bhutan", flag: "https://flagcdn.com/bt.svg" },
	{ name: "Republic of Peru", flag: "https://flagcdn.com/pe.svg" },
	{ name: "United States Minor Outlying Islands", flag: "https://flagcdn.com/um.svg" },
	{ name: "Republic of Kazakhstan", flag: "https://flagcdn.com/kz.svg" },
	{ name: "Gabonese Republic", flag: "https://flagcdn.com/ga.svg" },
	{ name: "Republic of Liberia", flag: "https://flagcdn.com/lr.svg" },
	{ name: "Swiss Confederation", flag: "https://flagcdn.com/ch.svg" },
	{ name: "State of Qatar", flag: "https://flagcdn.com/qa.svg" },
	{ name: "Argentine Republic", flag: "https://flagcdn.com/ar.svg" },
	{ name: "Falkland Islands", flag: "https://flagcdn.com/fk.svg" },
	{ name: "Guam", flag: "https://flagcdn.com/gu.svg" },
	{ name: "Republic of Panama", flag: "https://flagcdn.com/pa.svg" },
	{ name: "Saint Pierre and Miquelon", flag: "https://flagcdn.com/pm.svg" },
	{ name: "Bonaire, Sint Eustatius and Saba", flag: "https://flagcdn.com/bq.svg" },
	{ name: "Kingdom of Norway", flag: "https://flagcdn.com/no.svg" },
	{ name: "Turks and Caicos Islands", flag: "https://flagcdn.com/tc.svg" },
	{ name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/ba.svg" },
	{ name: "Republic of Mali", flag: "https://flagcdn.com/ml.svg" },
	{ name: "Burkina Faso", flag: "https://flagcdn.com/bf.svg" },
	{
		name: "Islamic Republic of Afghanistan",
		flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
	},
	{ name: "Republic of Slovenia", flag: "https://flagcdn.com/si.svg" },
	{ name: "Guiana", flag: "https://flagcdn.com/gf.svg" },
	{ name: "Iceland", flag: "https://flagcdn.com/is.svg" },
	{ name: "Republic of Bulgaria", flag: "https://flagcdn.com/bg.svg" },
	{ name: "Georgia", flag: "https://flagcdn.com/ge.svg" },
	{ name: "Montserrat", flag: "https://flagcdn.com/ms.svg" },
	{ name: "Republic of Ireland", flag: "https://flagcdn.com/ie.svg" },
	{ name: "Republic of Burundi", flag: "https://flagcdn.com/bi.svg" },
	{ name: "Commonwealth of the Northern Mariana Islands", flag: "https://flagcdn.com/mp.svg" },
	{ name: "Grenada", flag: "https://flagcdn.com/gd.svg" },
	{ name: "Kingdom of Belgium", flag: "https://flagcdn.com/be.svg" },
	{ name: "Republic of Albania", flag: "https://flagcdn.com/al.svg" },
	{ name: "Kingdom of Denmark", flag: "https://flagcdn.com/dk.svg" },
	{ name: "Republic of Colombia", flag: "https://flagcdn.com/co.svg" },
	{ name: "Republic of Lithuania", flag: "https://flagcdn.com/lt.svg" },
	{ name: "Bailiwick of Jersey", flag: "https://flagcdn.com/je.svg" },
	{ name: "State of Kuwait", flag: "https://flagcdn.com/kw.svg" },
	{ name: "People's Republic of Bangladesh", flag: "https://flagcdn.com/bd.svg" },
	{ name: "Republic of the Gambia", flag: "https://flagcdn.com/gm.svg" },
	{ name: "Pitcairn Group of Islands", flag: "https://flagcdn.com/pn.svg" },
	{ name: "Sahrawi Arab Democratic Republic", flag: "https://flagcdn.com/eh.svg" },
	{ name: "Socialist Republic of Vietnam", flag: "https://flagcdn.com/vn.svg" },
	{ name: "R\u00e9union Island", flag: "https://flagcdn.com/re.svg" },
	{ name: "Federal Republic of Germany", flag: "https://flagcdn.com/de.svg" },
	{ name: "Republic of Ecuador", flag: "https://flagcdn.com/ec.svg" },
	{ name: "Hungary", flag: "https://flagcdn.com/hu.svg" },
	{ name: "Federal Democratic Republic of Ethiopia", flag: "https://flagcdn.com/et.svg" },
	{ name: "Saint Lucia", flag: "https://flagcdn.com/lc.svg" },
	{ name: "Republic of Vanuatu", flag: "https://flagcdn.com/vu.svg" },
	{ name: "Democratic People's Republic of Korea", flag: "https://flagcdn.com/kp.svg" },
	{ name: "Kingdom of the Netherlands", flag: "https://flagcdn.com/nl.svg" },
	{ name: "Republic of Guatemala", flag: "https://flagcdn.com/gt.svg" },
	{ name: "Russian Federation", flag: "https://flagcdn.com/ru.svg" },
	{ name: "United Mexican States", flag: "https://flagcdn.com/mx.svg" },
	{ name: "Republic of the Marshall Islands", flag: "https://flagcdn.com/mh.svg" },
	{ name: "Martinique", flag: "https://flagcdn.com/mq.svg" },
	{ name: "Republic of Chile", flag: "https://flagcdn.com/cl.svg" },
	{
		name: "Macao Special Administrative Region of the People's Republic of China",
		flag: "https://flagcdn.com/mo.svg",
	},
	{ name: "Republic of Costa Rica", flag: "https://flagcdn.com/cr.svg" },
	{ name: "Republic of Djibouti", flag: "https://flagcdn.com/dj.svg" },
	{ name: "Japan", flag: "https://flagcdn.com/jp.svg" },
	{ name: "Republic of Azerbaijan", flag: "https://flagcdn.com/az.svg" },
	{ name: "Republic of Malawi", flag: "https://flagcdn.com/mw.svg" },
	{ name: "Republic of El Salvador", flag: "https://flagcdn.com/sv.svg" },
	{ name: "State of Israel", flag: "https://flagcdn.com/il.svg" },
	{ name: "Republic of Kenya", flag: "https://flagcdn.com/ke.svg" },
	{ name: "Cook Islands", flag: "https://flagcdn.com/ck.svg" },
	{ name: "Republic of South Sudan", flag: "https://flagcdn.com/ss.svg" },
	{ name: "Democratic Republic of Timor-Leste", flag: "https://flagcdn.com/tl.svg" },
	{ name: "Republic of Poland", flag: "https://flagcdn.com/pl.svg" },
	{ name: "Anguilla", flag: "https://flagcdn.com/ai.svg" },
	{ name: "Barbados", flag: "https://flagcdn.com/bb.svg" },
	{ name: "Republic of Turkey", flag: "https://flagcdn.com/tr.svg" },
	{ name: "Republic of Belarus", flag: "https://flagcdn.com/by.svg" },
	{ name: "Republic of Guinea-Bissau", flag: "https://flagcdn.com/gw.svg" },
	{ name: "Republic of Nicaragua", flag: "https://flagcdn.com/ni.svg" },
	{ name: "Commonwealth of Puerto Rico", flag: "https://flagcdn.com/pr.svg" },
	{ name: "Lao People's Democratic Republic", flag: "https://flagcdn.com/la.svg" },
	{ name: "Hashemite Kingdom of Jordan", flag: "https://flagcdn.com/jo.svg" },
	{ name: "Republic of Moldova", flag: "https://flagcdn.com/md.svg" },
	{ name: "Democratic Republic of S\u00e3o Tom\u00e9 and Pr\u00edncipe", flag: "https://flagcdn.com/st.svg" },
	{ name: "Niue", flag: "https://flagcdn.com/nu.svg" },
	{ name: "Country of Cura\u00e7ao", flag: "https://flagcdn.com/cw.svg" },
	{ name: "Democratic Republic of the Congo", flag: "https://flagcdn.com/cd.svg" },
	{ name: "Lebanese Republic", flag: "https://flagcdn.com/lb.svg" },
	{ name: "Republic of the Union of Myanmar", flag: "https://flagcdn.com/mm.svg" },
	{ name: "Turkmenistan", flag: "https://flagcdn.com/tm.svg" },
	{ name: "Independent State of Samoa", flag: "https://flagcdn.com/ws.svg" },
	{ name: "New Caledonia", flag: "https://flagcdn.com/nc.svg" },
];
